#  服务器配置
server:
  port: 8089

spring:
  thymeleaf:
    prefix: classpath:static/
    suffix: .html
    mode: HTML
  datasource:
      # 项目执行的时候，会使用这里的数据库参数
      url: jdbc:mysql://localhost:3306/spring?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: mobile#123
      driver-class-name: com.mysql.jdbc.Driver


mybatis:
  # 指向实体类包路径
  type-aliases-package: com.example.demo.pojo
  # mapper xml 文件地址
  mapper-locations: classpath:mapper/*.xml
  # 检查 mybatis 配置是否存在，一般命名为 mybatis-config.xml
  check-config-location: true
  # 执行模式。默认是 SIMPLE
  executor-type: simple
